#!/usr/bin/env ruby
require 'typhoeus'
require 'yaml'
tasks = YAML.load_file(File.expand_path('../start_of_day.yml', __FILE__))

actions = tasks['actions']

# Open Apps
puts "Opening Apps..."
actions['open_applications'].each do |app|
  puts "*** Opening Application #{app} ***"
  `open /Applications/#{app}`
end

sleep 5

# Check sites
puts "Checking Sites..."
hydra = Typhoeus::Hydra.new
actions['check_sites'].each do |url|
  puts "*** Checking Site #{url} ***"
  request = Typhoeus::Request.new(url)
  request.on_complete do |response|
    puts "#{url} responded with #{response.code}"
    `open #{url}` unless response.code == 200
  end
  hydra.queue request
end
hydra.run

# Current Project
puts "Opening current project..."

projects = YAML.load_file(File.expand_path('../tasks.yml', __FILE__))
tasks    = projects['tasks']
# If I don't know the key, I have to do this ugliness...
project  = tasks.first.first
url      = tasks.first.last['url']

puts "*** Opening http://#{url} from project #{project} ***"

`open http://#{url}`

# Complete :D
puts "Start of day complete!"
